extends Node

signal battle_started
signal battle_finished

signal cursor_marked_unit

signal city_changed_build_type
signal city_captured
signal city_requested_unit
signal city_resisted_unit
signal city_updated_vision

signal introduction_pressed_start
signal introduction_selected_scenario

signal mouse_entered_city
signal mouse_exited_city
signal mouse_entered_unit
signal mouse_exited_unit

signal team_won

signal unit_attacked_unit
signal unit_changed_position
signal unit_disbanded
signal unit_updated_vision

signal units_selected_next
